

_imagine:
    resource: .
    type: imagine
 
oneup_uploader:
    resource: .
    type: uploader
 

eeemarv_message:
    resource: @EeemarvBundle/Controller/MessageController.php
    type: annotation
    
    
eeemarv_user:
    resource: @EeemarvBundle/Controller/UserController.php
    type: annotation
  
eeemarv_transaction:
    resource: @EeemarvBundle/Controller/TransactionController.php
    type: annotation 

eeemarv_category:
    resource: @EeemarvBundle/Controller/CategoryController.php
    type: annotation
    
eeemarv_place:
    resource: @EeemarvBundle/Controller/PlaceController.php
    type: annotation

eeemarv_fos_user:
    resource: @EeemarvBundle/Resources/config/routing/fos_user.yml
    prefix: /    


eeemarv_default:
    resource: @EeemarvBundle/Controller/DefaultController.php
    type: annotation

eeemarv_comment:
    resource: @EeemarvBundle/Controller/CommentController.php
    type: annotation 

eeemarv_trash:
    resource: @EeemarvBundle/Controller/TrashController.php
    type: annotation

    
#eeemarv_page:
#    resource: @EeemarvBundle/Controller/PageController.php
#    type: annotation    

gallery:
    resource: @SonataMediaBundle/Resources/config/routing/gallery.xml
    prefix: /media/gallery

media:
    resource: @SonataMediaBundle/Resources/config/routing/media.xml
    prefix: /media


admin:
    resource: @SonataAdminBundle/Resources/config/routing/sonata_admin.xml
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin


sonata_page_exceptions:
    resource: @SonataPageBundle/Resources/config/routing/exceptions.xml
    prefix: /

sonata_page_cache:
    resource: @SonataPageBundle/Resources/config/routing/cache.xml
    prefix: /


eeemarv_missing_locale:
    pattern: /
    options: { i18n: false }
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: eeemarv_homepage
        permanent: true # 301 redirect

