

_imagine:
    resource: .
    type: imagine
 
oneup_uploader:
    resource: .
    type: uploader
 

eeemarv_message:
    resource: @EeemarvBundle/Controller/MessageController.php
    type: annotation
    
    
eeemarv_user:
    resource: @EeemarvBundle/Controller/UserController.php
    type: annotation
  
eeemarv_transaction:
    resource: @EeemarvBundle/Controller/TransactionController.php
    type: annotation 

eeemarv_category:
    resource: @EeemarvBundle/Controller/CategoryController.php
    type: annotation
    
eeemarv_place:
    resource: @EeemarvBundle/Controller/PlaceController.php
    type: annotation

eeemarv_fos_user:
    resource: @EeemarvBundle/Resources/config/routing/fos_user.yml
    prefix: /    


eeemarv_default:
    resource: @EeemarvBundle/Controller/DefaultController.php
    type: annotation

eeemarv_comment:
    resource: @EeemarvBundle/Controller/CommentController.php
    type: annotation 

eeemarv_trash:
    resource: @EeemarvBundle/Controller/TrashController.php
    type: annotation

    
eeemarv_page:
    resource: @EeemarvBundle/Controller/PageController.php
    type: annotation    
    
  

eeemarv_missing_locale:
    pattern: /
    options: { i18n: false }
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: eeemarv_pages
        permanent: true # 301 redirect

