
imports:
    - { resource: parameters.yml }
    - { resource: security.yml }


framework:
    #esi:             ~
    translator: { fallback: %locale% }
    secret: %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form: ~
    csrf_protection: true
    validation: { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale: "%locale%"
    trusted_proxies: ~
    session: ~
    fragments: ~
    http_method_override: true

# Twig Configuration

twig:
    debug: %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        locales: %locales%
        currency_rate: %currency_rate%
        new_user_days: %new_user_days%
#    form:
#        resources:
#            - EeemarvBundle:Form:fields.html.twig       
      
# Assetic Configuration

assetic:
    debug: %kernel.debug%
    use_controller: false
    bundles: [ EeemarvBundle ]
    filters:
        less:
            node: /usr/bin/node   #move this to parameters
            node_paths: [/usr/lib/node_modules]  #move this to parameters
            apply_to: "\.less$"           
#        lessphp:
#            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
#            apply_to: "\.less$"
#            preserve_comments: false   
        cssrewrite: ~

       


# Doctrine Configuration

doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        path:     %database_path%           
        charset:  UTF8
        types:
            datetime: Eeemarv\EeemarvBundle\DoctrineExtensions\DBAL\Types\UTCDateTimeType
            json: Sonata\Doctrine\Types\JsonType
       
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                auto_mapping: true
                dql:
                    numeric_functions:
                        GEO_DISTANCE: Eeemarv\EeemarvBundle\DQL\GeoDistanceFunction
                        GEO_PYTHA_DISTANCE: Eeemarv\EeemarvBundle\DQL\GeoPythagorasDistanceFunction        


# Swiftmailer Configuration

swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }


## 

# eeemarv

eeemarv:
    code:          %code%
    locales:       %locales%
    currency_rate: %currency_rate%



# ewz recaptcha

ewz_recaptcha:
    public_key: %recaptcha_public%
    private_key: %recaptcha_private%
    secure: false
    locale_key: kernel.default_locale
    enabled: true



# doctrine extensions

stof_doctrine_extensions:
    default_locale: %locale%
    translation_fallback: true
    orm:
        default:
            timestampable: true
            sluggable: true
            blameable: true
            translatable: true
            tree: true
            loggable: true
            uploadable: true
            softdeleteable: true
            sortable: true


# fos user

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Eeemarv\EeemarvBundle\Entity\User
    registration:
        form:
            type: eeemarv_registration_type
        confirmation:
            enabled: true
            template: EeemarvBundle:Registration:email.txt.twig
    profile:
        form:
            type: eeemarv_profile_type
    from_email:
        address: noreply@eeemarv.net
        sender_name: eeeMarv
    service:
        user_manager: eeemarv.user_manager 


# vich geografical

vich_geographical:
    db_driver: orm


# liip imagine    
 
liip_imagine:
    cache_prefix: /images-cache
    filter_sets:
        thumb100x100: 
            filters: 
                thumbnail: { size: [100, 100], mode: outbound }
               
               


# jms i18n


jms_i18n_routing:
    default_locale: %locale%
    locales: %locales%
    strategy: prefix_except_default



# ivory ck editor

ivory_ck_editor:
    configs:
        eeemarv_message:
            toolbar: "toolbar_message"
#            uiColor: "#222"
        eeemarv_page:
            toolbar: "toolbar_page"
#            uiColor: "#222"              
    toolbars:
        configs:
            toolbar_message: ["@document", "@basic", "@paragraph", "@link", "@tools"]
            toolbar_page: ["@document", "@basic", "@paragraph", "@link", "@tools"] 
        items:
            document: ["Source"]
            basic: ["Bold", "Underline", "Italic", "Blockquote", "Font", "FontSize", "TextColor"]
            paragraph: ["NumberedList", "BulletedList", "JustifyLeft", "JustifyCenter", "JustifyRight"]
            link: ["Link", "Unlink"]
            tools: ["Maximize"]
 
 
 # lexik maintenance


lexik_maintenance:
    driver:
        class: Lexik\Bundle\MaintenanceBundle\Drivers\FileDriver    
        options: {file_path: %kernel.root_dir%/cache/lock}   



# braincrafted bootstrap

braincrafted_bootstrap:
    less_filter: less
    jquery_path: %kernel.root_dir%/../web/bundles/bmatznerjquery/js/jquery.js


# guzzle

guzzle:
    plugin:
        wsse:
            username: %unique_id%
            
# oneup uploader

oneup_uploader:
    mappings:
        gallery:
            namer: eeemarv.file_namer
            frontend: blueimp
            storage:
                type: gaufrette
                filesystem: gaufrette.gallery_filesystem

# knp gaufrette

knp_gaufrette:
    adapters:
        gallery:
            local:
                directory: %kernel.root_dir%/../web/uploads
                create: false
    filesystems:
        gallery:
            adapter: gallery

# lsw memcache

lsw_memcache:
    session:
        client: default
    clients:
        default:
            hosts:
              - { dsn: localhost, port: 11211 }


# sonata block

sonata_block:
    context_manager: sonata.page.block.context_manager
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        #sonata.admin_doctrine_orm.block.audit:
        #    contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.rss:

        # Some specific block from the SonataMediaBundle
        #sonata.media.block.media:
        #sonata.media.block.gallery:
        #sonata.media.block.feature_media:


#sonata page 

sonata_page:
    multisite: host
    use_streamed_response: false #false in debug mode     
    default_template: default # template key from templates section, used as default
    ignore_route_patterns:
        - ^(.*)admin(.*)   # ignore admin route, ie route containing 'admin'
        - ^_(.*)          # ignore symfony routes

    ignore_routes:
        - sonata_page_cache_esi
        - sonata_page_cache_ssi
        - sonata_page_js_sync_cache
        - sonata_page_js_async_cache
        - sonata_cache_esi
        - sonata_cache_ssi
        - sonata_cache_js_async
        - sonata_cache_js_sync
        - sonata_cache_apc

    page_defaults:
        homepage: {decorate: false} # disable decoration for homepage, key - is a page route

    default_template: default # template key from templates section, used as default for pages
    templates:
        default:  { path: 'SonataPageBundle::layout.html.twig',          name: 'default' }
        2columns: { path: 'SonataPageBundle::2columns_layout.html.twig', name: '2 columns layout' }

    # manage the http errors
    catch_exceptions:
        not_found: [404]    # render 404 page with "not_found" key (name generated: _page_internal_error_{key})
        fatal:     [500]    # so you can use the same page for different http errors or specify specific page for each error    
    
    
    
    templates:
        default:  { path: 'SonataPageBundle::layout.html.twig',          name: 'default' }
        2columns: { path: 'SonataPageBundle::2columns_layout.html.twig', name: '2 columns layout' }

# cmf routing 

cmf_routing:
    chain:
        routers_by_id:
            sonata.page.router: 150
            jms_i18n_routing.router: 100
